# Generated by Django 4.2.14 on 2025-11-27 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, null=True, unique=True)),
                ('description', models.TextField(default='No description provided')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('is_phishing', models.BooleanField(default=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('depth', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='training.category')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('email', 'Email'), ('fake_login', 'Fake Login'), ('notice', 'Security Notice'), ('call', 'Voice Call'), ('form', 'Data Form'), ('reward', 'Reward Offer'), ('summary', 'Summary/Reflection')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('link_slug', models.SlugField(blank=True, default='', max_length=140)),
                ('form_schema', models.JSONField(blank=True, null=True)),
                ('timer_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('risk_type', models.CharField(blank=True, max_length=250, null=True)),
                ('risk_message', models.TextField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='training.scenario')),
            ],
            options={
                'verbose_name': 'Scenario step',
                'verbose_name_plural': 'Scenarios step',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserScenarioRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('next_remaining', models.IntegerField(default=0)),
                ('back_count', models.IntegerField(default=0)),
                ('next_count', models.IntegerField(default=0)),
                ('depth_max', models.IntegerField(default=0)),
                ('step_index', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('context', models.JSONField(default=dict)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('next', 'Next'), ('back', 'Back'), ('click', 'Clicked Link'), ('submit', 'Submit Form'), ('report', 'Report Phish'), ('timeout', 'Timer Exceeded')], max_length=20)),
                ('delta', models.IntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='training.userscenariorun')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.scenariostep')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('timer_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('score_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_steps', to='training.scenario')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='scenariostep',
            index=models.Index(fields=['scenario'], name='training_sc_scenari_5c397b_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenariostep',
            constraint=models.UniqueConstraint(fields=('scenario', 'order'), name='uniq_scenario_order'),
        ),
    ]
