# Generated by Django 4.2.23 on 2025-09-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='email_body_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='email_subject_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='title_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
