# Generated by Django 4.2.14 on 2025-11-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscenariorun',
            name='last_risk_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
