# Generated by Django 4.2.23 on 2025-09-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_scenario_email_body_ar_scenario_email_subject_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='email_body',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='email_body_ar',
            new_name='message_ar',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='email_subject',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='email_subject_ar',
        ),
    ]
