# Generated by Django 4.2.14 on 2025-12-12 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0002_userscenariorun_last_risk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='phase',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First (Baseline)'), (2, 'Second (Follow-up)')], default=1),
        ),
        migrations.CreateModel(
            name='ScenarioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.CharField(max_length=64)),
                ('step', models.IntegerField(default=0)),
                ('action', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
