# Generated by Django 4.2.23 on 2025-09-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_rename_email_body_scenario_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
