# Generated by Django 4.2.25 on 2025-10-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_category_alter_scenario_options_scenario_content_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['category', 'difficulty'], name='training_sc_categor_ea22ab_idx'),
        ),
    ]
