# Generated by Django 4.2.25 on 2025-10-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_scenario_training_sc_categor_ea22ab_idx'),
    ]

    operations = [
    ]
