# Generated by Django 4.2.25 on 2025-10-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_add_scenario_category_difficulty_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='message_ar',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='title_ar',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
