# Generated by Django 4.2.25 on 2025-10-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_remove_category_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
