# Generated by Django 4.2.25 on 2025-10-16 21:52

from django.db import migrations
from django.utils.text import slugify

def gen_unique_slug(name, taken):
    base = slugify(name, allow_unicode=True) or "category"
    candidate = base
    i = 2
    while candidate in taken:
        candidate = f"{base}-{i}"
        i += 1
    taken.add(candidate)
    return candidate

def forwards(apps, schema_editor):
    Category = apps.get_model("training", "Category")

    taken = set(
        Category.objects.exclude(slug__isnull=True).exclude(slug="").values_list("slug", flat=True)
    )
    for c in Category.objects.all():
        if not c.slug or c.slug == "":
            c.slug = gen_unique_slug(c.name, taken)
            c.save(update_fields=["slug"])

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("training", "0009_alter_category_slug"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
