# Generated by Django 4.2.25 on 2025-10-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_backfill_category_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
