# Generated by Django 4.2.25 on 2025-10-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='No description provided'),
            preserve_default=False,
        ),
    ]
