# Generated by Django 4.2.25 on 2025-10-24 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0012_alter_category_description'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS training_sc_categor_ea22ab_idx;
            DROP INDEX IF EXISTS training_scenario_category_id_f3f8ef5f;
            """,
            reverse_sql="-- noop",
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('email', 'Email'), ('fake_login', 'Fake Login'), ('notice', 'Security Notice'), ('call', 'Voice Call'), ('form', 'Data Form'), ('reward', 'Reward Offer'), ('summary', 'Summary/Reflection')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('link_slug', models.SlugField(blank=True, default='', max_length=140)),
                ('form_schema', models.JSONField(blank=True, null=True)),
                ('timer_seconds', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('next', 'Next'), ('back', 'Back'), ('click', 'Clicked Link'), ('submit', 'Submit Form'), ('report', 'Report Phish'), ('timeout', 'Timer Exceeded')], max_length=20)),
                ('delta', models.IntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserScenarioRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('next_remaining', models.IntegerField(default=0)),
                ('back_count', models.IntegerField(default=0)),
                ('next_count', models.IntegerField(default=0)),
                ('depth_max', models.IntegerField(default=0)),
                ('step_index', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('context', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='depth',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='userscenariorun',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.scenario'),
        ),
        migrations.AddField(
            model_name='userscenariorun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraction',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='training.userscenariorun'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.scenariostep'),
        ),
        migrations.AddField(
            model_name='scenariostep',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='training.scenario'),
        ),
        migrations.AddIndex(
            model_name='scenariostep',
            index=models.Index(fields=['scenario'], name='training_sc_scenari_5c397b_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenariostep',
            constraint=models.UniqueConstraint(fields=('scenario', 'order'), name='uniq_scenario_order'),
        ),
    ]
