# Generated by Django 4.2.25 on 2025-10-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_scenariostep_useraction_userscenariorun_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scenario',
            name='training_sc_categor_ea22ab_idx',
        ),
    ]
